export const banks: { [key: string]: any } = {
    'Banrisul': require('../assets/images/banks/banrisul.png'),
    'Banco do Brasil': require('../assets/images/banks/bb.png'),
    'Bradesco': require('../assets/images/banks/bradesco.png'),
    'C6': require('../assets/images/banks/c6bank.png'),
    'Caixa': require('../assets/images/banks/caixa.png'),
    'Clear': require('../assets/images/banks/clear.png'),
    'Daycoval': require('../assets/images/banks/daycoval.png'),
    'Inter': require('../assets/images/banks/inter.png'),
    'Itaú': require('../assets/images/banks/itau.png'),
    'Mercado Pago': require('../assets/images/banks/mercadopago.png'),
    'Next': require('../assets/images/banks/next.png'),
    'Nubank': require('../assets/images/banks/nubank.png'),
    'PagBank': require('../assets/images/banks/pagbank.png'),
    'Pagseguro': require('../assets/images/banks/pagseguro.png'),
    'PayPal': require('../assets/images/banks/paypal.png'),
    'PicPay': require('../assets/images/banks/picpay.png'),
    'Rico': require('../assets/images/banks/rico.png'),
    'Santander': require('../assets/images/banks/santander.png'),
    'Sofisa Direto': require('../assets/images/banks/sofisadireto.png'),
    'XP Investimentos': require('../assets/images/banks/xp.png'),
};  